;;; chatgpt-shell-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from chatgpt-shell.el

(autoload 'chatgpt-shell "chatgpt-shell" "\
Start a ChatGPT shell interactive command.

With NEW-SESSION, start a new session.

(fn &optional NEW-SESSION)" t)
(register-definition-prefixes "chatgpt-shell" '("chatgpt-shell-"))

;;; End of scraped data

(provide 'chatgpt-shell-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; chatgpt-shell-autoloads.el ends here
