#!/bin/bash

# Show the git branch and dirty state in the prompt.
# Borrowed from: http://henrik.nyh.se/2008/12/git-dirty-prompt
function parse_git_dirty {
    [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo "*"
}

function parse_git_branch {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\(\1$(parse_git_dirty)\)/"
}

# if [ `which git` ]; then
#     function git_prompt {
#         parse_git_branch
#     }
# else
#     function git_prompt {
#         echo ""
#     }
# fi

if [ "\$(type -t __git_ps1)" ]; then
   export PS1="[\u@\h \W\$(__git_ps1 '(%s)')]$ "
fi
