;;; prodigy-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from prodigy.el

(autoload 'prodigy-add-filter "prodigy" "\
Add filter TYPE, that filters for VALUE.

(fn TYPE VALUE)")
(autoload 'prodigy-define-service "prodigy" "\
Define a new service with ARGS.

If service with that name already exists, the service is updated.
The old service process is transferred to the new service.

(fn &rest ARGS)")
(function-put 'prodigy-define-service 'lisp-indent-function 'defun)
(autoload 'prodigy-define-tag "prodigy" "\
Define a new tag with ARGS.

(fn &rest ARGS)")
(function-put 'prodigy-define-tag 'lisp-indent-function 'defun)
(autoload 'prodigy-define-status "prodigy" "\
Define a new status with ARGS.

(fn &rest ARGS)")
(function-put 'prodigy-define-status 'lisp-indent-function 'defun)
(autoload 'prodigy-mode "prodigy" "\
Special mode for prodigy buffers.

(fn)" t)
(autoload 'prodigy-view-mode "prodigy" "\
Mode for viewing prodigy process output.

(fn)" t)
(autoload 'prodigy "prodigy" "\
Manage external services from within Emacs." t)
(register-definition-prefixes "prodigy" '("prodigy-"))

;;; End of scraped data

(provide 'prodigy-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; prodigy-autoloads.el ends here
