;;; ibuffer-projectile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ibuffer-projectile.el

 (autoload 'ibuffer-make-column-project-name "ibuffer-projectile")
 (autoload 'ibuffer-do-sort-by-project-name "ibuffer-projectile")
 (autoload 'ibuffer-make-column-project-relative-file "ibuffer-projectile")
(autoload 'ibuffer-projectile-generate-filter-groups "ibuffer-projectile" "\
Create a set of ibuffer filter groups based on the projectile root dirs of buffers.")
(autoload 'ibuffer-projectile-set-filter-groups "ibuffer-projectile" "\
Set the current filter groups to filter by projectile root dir." t)
(register-definition-prefixes "ibuffer-projectile" '("ibuffer-projectile-" "projectile-root"))

;;; End of scraped data

(provide 'ibuffer-projectile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ibuffer-projectile-autoloads.el ends here
