;;; msgu-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from msgu.el

(autoload 'msgu-inhibit-log "msgu" "\
Execute BODY without write it to message buffer.

(fn &rest BODY)" nil t)
(function-put 'msgu-inhibit-log 'lisp-indent-function 0)
(autoload 'msgu-silent "msgu" "\
Execute BODY without message.

(fn &rest BODY)" nil t)
(function-put 'msgu-silent 'lisp-indent-function 0)
(autoload 'msgu-unsilent "msgu" "\
Execute BODY with ensuring message log.

(fn &rest BODY)" nil t)
(function-put 'msgu-unsilent 'lisp-indent-function 0)
(autoload 'msgu-sleep "msgu" "\
Wrap `sleep-for' function width default SECONDS and MILLISECONDS.

(fn &optional SECONDS MILLISECONDS)")
(autoload 'msgu-sit "msgu" "\
Wrap `sit-for' function with default SECONDS and NODISP.

(fn &optional SECONDS NODISP)")
(autoload 'msgu-current "msgu" "\
Log messages with current message on top if available.

Arguments FMT and ARGS are used for format message.

(fn FMT &rest ARGS)")
(register-definition-prefixes "msgu" '("msgu-"))

;;; End of scraped data

(provide 'msgu-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; msgu-autoloads.el ends here
